/**
 * Public example profile.
 *
 * Replace ROLE_FAMILIES, LOCATION_GROUPS, exclusions, and language rules with
 * evidence-based criteria for your own search. Keep private profile data in a
 * private fork rather than committing it to a public repository.
 */
export const LOOKBACK_HOURS = 12;
export const REQUEST_TIMEOUT_MS = 12_000;
export const DEFAULT_ATS_BOARDS_PER_SOURCE = 400;
export const DEFAULT_MAX_SCAN_MINUTES = 18;
export const DEFAULT_MAX_PAGE_VERIFICATIONS = 60;

export const ROLE_FAMILIES = [
  {
    id: 'product-partner-marketing',
    label: 'Product / partner marketing',
    priority: 4,
    terms: [
      'product marketing',
      'product marketer',
      'partner marketing',
      'channel marketing',
      'ecosystem marketing',
      'alliance marketing',
      'alliances marketing',
      'go-to-market',
      'go to market',
      'gtm',
      'market development',
      'commercial marketing',
      'customer marketing',
      'solutions marketing',
      'portfolio marketing',
      'partner enablement',
      'sales enablement',
      'commercial enablement',
      'customer insights',
      'market intelligence',
      'proposition specialist',
      'proposition manager',
    ],
    responsibilityTerms: [
      'positioning',
      'messaging',
      'product launch',
      'go-to-market',
      'sales enablement',
      'partner enablement',
      'market research',
      'customer insight',
    ],
  },
  {
    id: 'sustainability-circularity',
    label: 'Sustainability / circularity',
    priority: 3.8,
    terms: [
      'sustainability',
      'sustainability specialist',
      'sustainability coordinator',
      'sustainability analyst',
      'sustainability advisor',
      'sustainability consultant',
      'sustainability engineer',
      'circular economy',
      'circularity',
      'circular business',
      'resource efficiency',
      'recommerce',
      'reverse logistics',
      'ecodesign',
      'eco-design',
      'product sustainability',
      'sustainable product',
      'climate program',
      'climate programme',
      'esg program',
      'esg programme',
      'impact specialist',
      'lifecycle specialist',
      'life cycle specialist',
      'environmental specialist',
      'industrial sustainability',
    ],
    responsibilityTerms: [
      'circular economy',
      'circular business',
      'resource efficiency',
      'reuse',
      'lifecycle information',
      'life cycle assessment',
      'ecodesign',
      'product sustainability',
      'sustainability program',
      'sustainability programme',
    ],
  },
  {
    id: 'growth-marketing',
    label: 'Growth marketing',
    priority: 3.4,
    terms: [
      'growth marketing',
      'growth marketer',
      'marketing specialist',
      'digital marketing specialist',
      'marketing coordinator',
      'content marketing',
      'content specialist',
      'growth specialist',
      'lifecycle marketing',
      'crm specialist',
      'crm marketing',
      'retention marketing',
      'engagement marketing',
      'activation specialist',
      'acquisition marketing',
      'demand generation',
      'digital growth',
      'conversion specialist',
      'campaign operations',
      'marketing operations',
      'marketing automation',
      'performance marketing',
      'content growth',
      'seo specialist',
      'e-commerce growth',
      'ecommerce growth',
      'customer journey',
      'marketing analyst',
      'growth analyst',
    ],
    responsibilityTerms: [
      'acquisition',
      'retention',
      'activation',
      'conversion',
      'customer journey',
      'marketing automation',
      'campaign operations',
      'experimentation',
      'seo',
      'answer engine optimization',
    ],
  },
  {
    id: 'product-operations-delivery',
    label: 'Product operations / delivery',
    priority: 3,
    terms: [
      'product operations',
      'product ops',
      'product specialist',
      'product coordinator',
      'program coordinator',
      'programme coordinator',
      'project coordinator',
      'program specialist',
      'programme specialist',
      'project specialist',
      'program analyst',
      'programme analyst',
      'project analyst',
      'implementation specialist',
      'implementation coordinator',
      'onboarding specialist',
      'service delivery',
      'delivery operations',
      'launch operations',
      'business operations',
      'commercial operations',
      'partner operations',
      'marketplace operations',
      'customer operations',
      'revenue operations',
      'operations specialist',
      'operations coordinator',
      'process improvement',
      'product enablement',
      'partnership coordinator',
      'markets analyst',
      'market analyst',
    ],
    responsibilityTerms: [
      'cross-functional delivery',
      'implementation',
      'onboarding',
      'service delivery',
      'process improvement',
      'marketplace operations',
      'partner operations',
      'product enablement',
      'program delivery',
      'programme delivery',
    ],
  },
];

export const TITLE_EXCLUDES = [
  'software engineer',
  'software developer',
  'data scientist',
  'bi specialist',
  'business intelligence',
  'machine learning',
  'doctoral',
  'postdoctoral',
  'phd position',
  'chief ',
  'vice president',
  'vp ',
  'director',
  'head of',
];

export const IC_TITLE_SIGNALS = [
  'specialist',
  'coordinator',
  'associate',
  'analyst',
  'consultant',
  'advisor',
  'adviser',
  'project lead',
  'program lead',
  'programme lead',
];

export const LOCATION_GROUPS = [
  {
    id: 'sweden',
    label: 'Sweden',
    score: 35,
    terms: [
      'sweden',
      'stockholm',
      'gothenburg',
      'göteborg',
      'malmö',
      'malmo',
      'lund',
      'linköping',
      'linkoping',
      'uppsala',
      'solna',
      'västerås',
      'vasteras',
      'helsingborg',
      'örebro',
      'orebro',
    ],
  },
  {
    id: 'amsterdam',
    label: 'Amsterdam',
    score: 25,
    terms: ['amsterdam'],
  },
  {
    id: 'vienna',
    label: 'Vienna',
    score: 18,
    terms: ['vienna', 'wien'],
  },
  {
    id: 'eu',
    label: 'Other EU / Europe-remote',
    score: 13,
    terms: [
      'europe',
      'european union',
      ' eu ',
      'emea',
      'remote',
      'netherlands',
      'rotterdam',
      'utrecht',
      'austria',
      'germany',
      'berlin',
      'hamburg',
      'munich',
      'münchen',
      'denmark',
      'copenhagen',
      'finland',
      'helsinki',
      'norway',
      'oslo',
      'belgium',
      'brussels',
      'france',
      'paris',
      'spain',
      'madrid',
      'barcelona',
      'portugal',
      'lisbon',
      'italy',
      'milan',
      'ireland',
      'dublin',
      'poland',
      'warsaw',
      'czech',
      'prague',
      'estonia',
      'tallinn',
      'latvia',
      'riga',
      'lithuania',
      'vilnius',
      'luxembourg',
      'slovenia',
      'slovakia',
      'croatia',
      'romania',
      'bucharest',
      'bulgaria',
      'greece',
      'athens',
      'hungary',
      'budapest',
      'cyprus',
      'malta',
    ],
  },
];

export const OBVIOUS_NON_EU_ONLY = [
  'united states only',
  'us only',
  'usa only',
  'canada only',
  'latin america only',
  'latam only',
  'india only',
  'australia only',
  'new zealand only',
  'apac only',
];

export const UNSUPPORTED_LOCAL_LANGUAGES = [
  'swedish',
  'dutch',
  'german',
  'french',
  'danish',
  'norwegian',
  'finnish',
  'italian',
  'spanish',
  'portuguese',
  'polish',
  'czech',
];

export const WTTJ_QUERIES = [
  'product marketing',
  'partner marketing',
  'go to market',
  'sustainability',
  'circular economy',
  'growth marketing',
  'marketing operations',
  'product operations',
  'implementation specialist',
  'service delivery',
];

export const ATS_DIRECTORIES = {
  greenhouse: 'https://raw.githubusercontent.com/Feashliaa/job-board-aggregator/main/data/greenhouse_companies.json',
  lever: 'https://raw.githubusercontent.com/Feashliaa/job-board-aggregator/main/data/lever_companies.json',
  ashby: 'https://raw.githubusercontent.com/Feashliaa/job-board-aggregator/main/data/ashby_companies.json',
  workday: 'https://raw.githubusercontent.com/Feashliaa/job-board-aggregator/main/data/workday_companies.json',
};

